version: '3.9'
services:

  app1: &app
    hostname: api1
    build:
      context: .
      dockerfile: Dockerfile

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.6'
    #       memory: '0.5GB'

    networks:
      - rinha-net

    environment:
      - PHP_VERSION="8.3"
      - DB_HOST=db
      - DB_USER=rinha
      - DB_PASSWORD=rinha
      - DB_NAME=rinha

  app2:
    <<: *app
    hostname: api2

  nginx: 
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1

    networks:
      - rinha-net

    ports:
      - "9999:9999"
      
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: '0.3GB'
    
  db:
    container_name: db
    image: postgres:15.4

    environment:
        POSTGRES_DB: rinha
        POSTGRES_PASSWORD: rinha
        POSTGRES_USER: rinha
        PGDATA: /var/lib/postgresql/data/db-files/

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - rinha-net

    ports:
      - "5432:5432"

    # deploy:
    #     resources:
    #         limits:
    #             cpus: '0.3'
    #             memory: '1.5GB'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - rinha-net

    volumes:
      - pgadmin-data:/var/lib/pgadmin
                
volumes:
  db-data:
  pgadmin-data:

              
networks: 
  rinha-net:
